name: Unit Test
on:
  push:
    branches:
      - "main"

jobs:
  backend_ci:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v3
    - name: 'Set up Go'
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: 'Unit tests'
      env:
        TESTCOVERAGE_THRESHOLD: 75
      run: |
        chmod +x ./test.sh 
        ./test.sh